# Main Navigation

main:
  - name: Bio
    url: /
    weight: 10

  - name: Research
    url: /research/
    weight: 20

  - name: Publications
    url: /publications/
    weight: 30

  - name: Projects
    url: /projects/
    weight: 40

  - name: Experience
    url: /experience/
    weight: 50

  - name: CV
    url: /uploads/cv.pdf
    weight: 60